### ISSUE TITLE
Падает на Sierra 10.12.1 (16B2555)

### ISSUE THREAD

**Issue by yaonya** [niki-timofe/NarodMonOSX#11]
Краш-логи:
[NarodMon_2016-10-30-034745_MacBook-Pro.crash.txt](https://github.com/niki-timofe/NarodMonOSX/files/560245/NarodMon_2016-10-30-034745_MacBook-Pro.crash.txt) (59КБ)
[NarodMon_2016-10-30-035042_MacBook-Pro.crash.txt](https://github.com/niki-timofe/NarodMonOSX/files/560244/NarodMon_2016-10-30-035042_MacBook-Pro.crash.txt) (47КБ)

**Comment by niki-timofe** [comment]
Будет исправлено в ближайшем обновлении
