### ISSUE TITLE
Crash while launching

### ISSUE THREAD

**Issue by tomshinsky** [niki-timofe/NarodMonOSX#13]
App crashes right after start. Crash report attached.
MacOS 10.12 (16A323), MacBook Pro (Retina, 13-inch, Late 2013)
https://yadi.sk/d/j2ZGn3OlyCuwd

**Comment by niki-timofe** [comment]
Please check [v2.0.0-alpha.1](https://github.com/niki-timofe/NarodMonOSX/releases/tag/v2.0.0-alpha.1)
