### ISSUE TITLE
Падает после сборки на 10.11.3

### ISSUE THREAD

**Issue by SimWhite** [niki-timofe/NarodMonOSX#8]
Собирается нормально, но после этого сразу падает со следующими ошибками:

<pre>
2016-01-20 20:49:00.941 NarodMon[3124:668900] An uncaught exception was raised
2016-01-20 20:49:00.941 NarodMon[3124:668900] *** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array
2016-01-20 20:49:00.941 NarodMon[3124:668900] (
    0   CoreFoundation                      0x00007fff84b67ae2 __exceptionPreprocess + 178
    1   libobjc.A.dylib                     0x00007fff85825f7e objc_exception_throw + 48
    2   CoreFoundation                      0x00007fff84a266f5 -[__NSArrayM objectAtIndex:] + 245
    3   NarodMon                            0x00000001000030e7 -[AppDelegate connectionDidFinishLoading:] + 423
    4   CFNetwork                           0x00007fff9a566129 __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 69
    5   CFNetwork                           0x00007fff9a56603e -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 233
    6   CFNetwork                           0x00007fff9a565f43 -[NSURLConnectionInternal _withActiveConnectionAndDelegate:] + 48
    7   CFNetwork                           0x00007fff9a56ace2 ___ZN27URLConnectionClient_Classic26_delegate_didFinishLoadingEU13block_pointerFvvE_block_invoke + 104
    8   CFNetwork                           0x00007fff9a6ff407 ___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2 + 100
    9   libdispatch.dylib                   0x0000000100039bf9 _dispatch_client_callout + 8
    10  libdispatch.dylib                   0x0000000100049e09 _dispatch_block_invoke + 920
    11  CFNetwork                           0x00007fff9a565e00 _ZN19RunloopBlockContext13_invoke_blockEPKvPv + 24
    12  CoreFoundation                      0x00007fff84a438f4 CFArrayApplyFunction + 68
    13  CFNetwork                           0x00007fff9a565cf9 _ZN19RunloopBlockContext7performEv + 137
    14  CFNetwork                           0x00007fff9a565b9a _ZN17MultiplexerSource7performEv + 282
    15  CFNetwork                           0x00007fff9a5659bc _ZN17MultiplexerSource8_performEPv + 72
    16  CoreFoundation                      0x00007fff84a775c1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    17  CoreFoundation                      0x00007fff84a6941c __CFRunLoopDoSources0 + 556
    18  CoreFoundation                      0x00007fff84a6893f __CFRunLoopRun + 927
    19  CoreFoundation                      0x00007fff84a68338 CFRunLoopRunSpecific + 296
    20  HIToolbox                           0x00007fff88d80935 RunCurrentEventLoopInMode + 235
    21  HIToolbox                           0x00007fff88d8076f ReceiveNextEventCommon + 432
    22  HIToolbox                           0x00007fff88d805af _BlockUntilNextEventMatchingListInModeWithFilter + 71
    23  AppKit                              0x00007fff970b20ee _DPSNextEvent + 1067
    24  AppKit                              0x00007fff9747e943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
    25  AppKit                              0x00007fff970a7fc8 -[NSApplication run] + 682
    26  AppKit                              0x00007fff9702a520 NSApplicationMain + 1176
    27  NarodMon                            0x00000001000066b2 main + 34
    28  libdyld.dylib                       0x00007fff97f4f5ad start + 1
    29  ???                                 0x0000000000000003 0x0 + 3
)
2016-01-20 20:49:00.942 NarodMon[3124:668900] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'
*** First throw call stack:
(
    0   CoreFoundation                      0x00007fff84b67ae2 __exceptionPreprocess + 178
    1   libobjc.A.dylib                     0x00007fff85825f7e objc_exception_throw + 48
    2   CoreFoundation                      0x00007fff84a266f5 -[__NSArrayM objectAtIndex:] + 245
    3   NarodMon                            0x00000001000030e7 -[AppDelegate connectionDidFinishLoading:] + 423
    4   CFNetwork                           0x00007fff9a566129 __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 69
    5   CFNetwork                           0x00007fff9a56603e -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 233
    6   CFNetwork                           0x00007fff9a565f43 -[NSURLConnectionInternal _withActiveConnectionAndDelegate:] + 48
    7   CFNetwork                           0x00007fff9a56ace2 ___ZN27URLConnectionClient_Classic26_delegate_didFinishLoadingEU13block_pointerFvvE_block_invoke + 104
    8   CFNetwork                           0x00007fff9a6ff407 ___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2 + 100
    9   libdispatch.dylib                   0x0000000100039bf9 _dispatch_client_callout + 8
    10  libdispatch.dylib                   0x0000000100049e09 _dispatch_block_invoke + 920
    11  CFNetwork                           0x00007fff9a565e00 _ZN19RunloopBlockContext13_invoke_blockEPKvPv + 24
    12  CoreFoundation                      0x00007fff84a438f4 CFArrayApplyFunction + 68
    13  CFNetwork                           0x00007fff9a565cf9 _ZN19RunloopBlockContext7performEv + 137
    14  CFNetwork                           0x00007fff9a565b9a _ZN17MultiplexerSource7performEv + 282
    15  CFNetwork                           0x00007fff9a5659bc _ZN17MultiplexerSource8_performEPv + 72
    16  CoreFoundation                      0x00007fff84a775c1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    17  CoreFoundation                      0x00007fff84a6941c __CFRunLoopDoSources0 + 556
    18  CoreFoundation                      0x00007fff84a6893f __CFRunLoopRun + 927
    19  CoreFoundation                      0x00007fff84a68338 CFRunLoopRunSpecific + 296
    20  HIToolbox                           0x00007fff88d80935 RunCurrentEventLoopInMode + 235
    21  HIToolbox                           0x00007fff88d8076f ReceiveNextEventCommon + 432
    22  HIToolbox                           0x00007fff88d805af _BlockUntilNextEventMatchingListInModeWithFilter + 71
    23  AppKit                              0x00007fff970b20ee _DPSNextEvent + 1067
    24  AppKit                              0x00007fff9747e943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
    25  AppKit                              0x00007fff970a7fc8 -[NSApplication run] + 682
    26  AppKit                              0x00007fff9702a520 NSApplicationMain + 1176
    27  NarodMon                            0x00000001000066b2 main + 34
    28  libdyld.dylib                       0x00007fff97f4f5ad start + 1
    29  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
</pre>

**Comment by niki-timofe** [comment]
@SimWhite, прошу прощения, что долго не отвечал, не было возможности заняться этим приложением. Возможно, я знаю в чем причина, но не могли бы Вы попробовать сейчас еще раз запустить приложение, а если оно опять упадет, скажите, во сколько оно было запущено (максимально точно), чтобы проверить логи.

**Comment by SimWhite** [comment]
Попробовал. Запуски:
Sat May 21 16:24:05 YEKT 2016
Sat May 21 16:24:33 YEKT 2016

Кстати, не помню уже раньше это было или нет, но сейчас подсвечивает [вот такую строку](https://xdrops.in/tKsqqVwgQkpFSSsutht2IFqw.png).

**Comment by niki-timofe** [comment]
А из релизов, уже собранная версия тоже падает?

**Comment by SimWhite** [comment]
Да. Взял самую последнюю только что. После запуска сразу закрывается, в логах:

```
21/05/16 17:50:42,366 NarodMon[16559]: An uncaught exception was raised
21/05/16 17:50:42,366 NarodMon[16559]: *** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array
21/05/16 17:50:42,366 NarodMon[16559]: (
    0   CoreFoundation                      0x00007fff869834f2 __exceptionPreprocess + 178
    1   libobjc.A.dylib                     0x00007fff8c21cf7e objc_exception_throw + 48
    2   CoreFoundation                      0x00007fff8689a7c5 -[__NSArrayM objectAtIndex:] + 245
    3   NarodMon                            0x000000010b252809 NarodMon + 10249
    4   CFNetwork                           0x00007fff90473acd __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 69
    5   CFNetwork                           0x00007fff904739e2 -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 233
    6   CFNetwork                           0x00007fff904738e7 -[NSURLConnectionInternal _withActiveConnectionAndDelegate:] + 48
    7   CFNetwork                           0x00007fff90478686 ___ZN27URLConnectionClient_Classic26_delegate_didFinishLoadingEU13block_pointerFvvE_block_invoke + 104
    8   CFNetwork                           0x00007fff9060d4bd ___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2 + 100
    9   libdispatch.dylib                   0x00007fff9937640b _dispatch_client_callout + 8
    10  libdispatch.dylib                   0x00007fff99384039 _dispatch_block_invoke + 474
    11  CFNetwork                           0x00007fff904737a4 _ZN19RunloopBlockContext13_invoke_blockEPKvPv + 24
    12  CoreFoundation                      0x00007fff868bad74 CFArrayApplyFunction + 68
    13  CFNetwork                           0x00007fff9047369d _ZN19RunloopBlockContext7performEv + 137
    14  CFNetwork                           0x00007fff9047353e _ZN17MultiplexerSource7performEv + 282
    15  CFNetwork                           0x00007fff90473360 _ZN17MultiplexerSource8_performEPv + 72
    16  CoreFoundation                      0x00007fff86918881 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    17  CoreFoundation                      0x00007fff868f7fbc __CFRunLoopDoSources0 + 556
    18  CoreFoundation                      0x00007fff868f74df __CFRunLoopRun + 927
    19  CoreFoundation                      0x00007fff868f6ed8 CFRunLoopRunSpecific + 296
    20  HIToolbox                           0x00007fff91a75935 RunCurrentEventLoopInMode + 235
    21  HIToolbox                           0x00007fff91a7576f ReceiveNextEventCommon + 432
    22  HIToolbox                           0x00007fff91a755af _BlockUntilNextEventMatchingListInModeWithFilter + 71
    23  AppKit                              0x00007fff98756df6 _DPSNextEvent + 1067
    24  AppKit                              0x00007fff98756226 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
    25  AppKit                              0x00007fff9874ad80 -[NSApplication run] + 682
    26  AppKit                              0x00007fff98714368 NSApplicationMain + 1176
    27  libdyld.dylib                       0x00007fff8fa585ad start + 1
    28  ???                                 0x0000000000000001 0x0 + 1
)
21/05/16 17:50:42,366 NarodMon[16559]: *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'
*** First throw call stack:
(
    0   CoreFoundation                      0x00007fff869834f2 __exceptionPreprocess + 178
    1   libobjc.A.dylib                     0x00007fff8c21cf7e objc_exception_throw + 48
    2   CoreFoundation                      0x00007fff8689a7c5 -[__NSArrayM objectAtIndex:] + 245
    3   NarodMon                            0x000000010b252809 NarodMon + 10249
    4   CFNetwork                           0x00007fff90473acd __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 69
    5   CFNetwork                           0x00007fff904739e2 -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 233
    6   CFNetwork                           0x00007fff904738e7 -[NSURLConnectionInternal _withActiveConnectionAndDelegate:] + 48
    7   CFNetwork                           0x00007fff90478686 ___ZN27URLConnectionClient_Classic26_delegate_didFinishLoadingEU13block_pointerFvvE_block_invoke + 104
    8   CFNetwork                           0x00007fff9060d4bd ___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2 + 100
    9   libdispatch.dylib                   0x00007fff9937640b _dispatch_client_callout + 8
    10  libdispatch.dylib                   0x00007fff99384039 _dispatch_block_invoke + 474
    11  CFNetwork                           0x00007fff904737a4 _ZN19RunloopBlockContext13_invoke_blockEPKvPv + 24
    12  CoreFoundation                      0x00007fff868bad74 CFArrayApplyFunction + 68
    13  CFNetwork                           0x00007fff9047369d _ZN19RunloopBlockContext7performEv + 137
    14  CFNetwork                           0x00007fff9047353e _ZN17MultiplexerSource7performEv + 282
    15  CFNetwork                           0x00007fff90473360 _ZN17MultiplexerSource8_performEPv + 72
    16  CoreFoundation                      0x00007fff86918881 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    17  CoreFoundation                      0x00007fff868f7fbc __CFRunLoopDoSources0 + 556
    18  CoreFoundation                      0x00007fff868f74df __CFRunLoopRun + 927
    19  CoreFoundation                      0x00007fff868f6ed8 CFRunLoopRunSpecific + 296
    20  HIToolbox                           0x00007fff91a75935 RunCurrentEventLoopInMode + 235
    21  HIToolbox                           0x00007fff91a7576f ReceiveNextEventCommon + 432
    22  HIToolbox                           0x00007fff91a755af _BlockUntilNextEventMatchingListInModeWithFilter + 71
    23  AppKit                              0x00007fff98756df6 _DPSNextEvent + 1067
    24  AppKit                              0x00007fff98756226 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
    25  AppKit                              0x00007fff9874ad80 -[NSApplication run] + 682
    26  AppKit                              0x00007fff98714368 NSApplicationMain + 1176
    27  libdyld.dylib                       0x00007fff8fa585ad start + 1
    28  ???                                 0x0000000000000001 0x0 + 1
)
```

**Comment by niki-timofe** [comment]
Ага, понял, сегодня - завтра исправлю

**Comment by niki-timofe** [comment]
Будет исправлено в версии 2.0.0
